import { Category } from './types';

export const INITIAL_CATEGORIES_RAW = [
  "Навигация - Оперативно ниво | Navigation - Operational level",
  "Товарно дело - Оперативно ниво | Cargo handling and stowage - Operational level",
  "Грижа за лицата на борда - Оперативно ниво | Care for persons on board - Operational level",
  "МППСМ - Оперативно и Управленско ниво | COLREG - Operational and Management level",
  "Навигация - Управленско ниво | Navigation - Management level",
  "Товарно дело - Управленско ниво | Cargo handling and stowage - Management level",
  "Грижата лицата на борда - Управленско ниво | Care for persons on board - Management level",
  "Корабен радиооператор за СМСББ - GOC | GOC - GMDSS",
  "ЕЕАСУ - Оперативно ниво | Electrical equipment and control system - Operational level",
  "Морско инжинерство - Оперативно ниво | Marine Engineering - Operational level",
  "Техническо поддържане и ремонт - Оперативно ниво | Part Maintenance and Repair - Operational level",
  "УЕКГЛБ - Оперативно ниво | Controlling the operation of the ship - Operational level",
  "ЕЕАСУ - Управленско ниво | Electrical equipment - Management level",
  "Морско инжинерство - Управленско ниво | Marine Engineering - Management level",
  "Техническо поддържане и ремонт - Управленско ниво | Maintenance - Management level",
  "УЕКГЛБ - Управленско ниво | Controlling operation - Management level",
  "Водач на кораб до 40 БТ | Skipper up to 40 GT",
  "Водач на кораб до 40 БТ - на руски език | Skipper up to 40 GT - Russian",
  "Елмеханик електрообзавеждане - Оперативно | Electro-technical - Equipment",
  "Елмеханик поддържане и ремонт - Оперативно | Electro-technical - Maintenance",
  "Елмеханик УЕКГЛБ - Оперативно | Electro-technical - Operation",
  "Грижа за лицата на борда - Оперативно ниво стар | Care for persons (Old) - Operational",
  "Навигация - Оперативно ниво Стар | Navigation (Old) - Operational",
  "Товарно дело - Оперативно ниво стар | Cargo (Old) - Operational"
];

export const TRANSLATIONS = {
  bg: {
    login: "Вход",
    register: "Регистрация",
    email: "Имейл",
    password: "Парола",
    firstName: "Име",
    lastName: "Фамилия",
    confirmPass: "Потвърди парола",
    home: "Начало",
    myTests: "Моите тестове",
    functions: "Функции",
    contact: "Контакт",
    logout: "Изход",
    adminPanel: "Админ Панел",
    welcome: "Добре дошли в Морски Тестове",
    subWelcome: "Подгответе се за вашите изпити професионално.",
    startTest: "Започни Тест",
    requestAccess: "Заяви Достъп",
    status: "Статус",
    approved: "Одобрен",
    pending: "Чакащ",
    price: "Цена",
    totalPrice: "Обща цена",
    revolutMsg: "Моля изпратете сумата на следния Revolut линк, като посочите вашия имейл като основание:",
    users: "Потребители",
    categories: "Категории",
    requests: "Заявки",
    import: "Импорт",
    packages: "Пакети",
    uploadExcel: "Качи Excel Файл",
    generateTest: "Генерирай Тест",
    timeLeft: "Оставащо време",
    submit: "Предай теста",
    send: "Изпрати",
    score: "Резултат",
    question: "Въпрос",
    prev: "Предишен",
    next: "Следващ",
    suspend: "Блокирай",
    activate: "Активирай",
    changePass: "Смяна парола",
    save: "Запази",
    cancel: "Отказ",
    noTests: "Нямате активни категории. Моля заявете достъп от меню Функции.",
    completed: "Приключен",
    congrats: "Тестът приключи!",
    failed: "Слаб",
    passed: "Среден",
    good: "Добър",
    veryGood: "Много добър",
    excellent: "Отличен",
    settings: "Настройки",
    revolutLink: "Revolut Линк",
    facebookLink: "Facebook Линк",
    announcement: "Съобщение (Лента)",
    followUs: "Последвайте ни във Facebook",
    contactUs: "Свържете се с нас",
    addCategory: "Добави Категория",
    addPackage: "Добави Пакет",
    edit: "Редактирай",
    delete: "Изтрий",
    nameBg: "Име (BG)",
    nameEn: "Име (EN)",
    duration: "Времетраене (мин)",
    questions: "Въпроси",
    create: "Създай",
    packageIncludes: "Пакетът включва:",
    individual: "Индивидуални Функции",
    bundle: "ПРОМО ПАКЕТИ",
    approvalSettings: "Настройки за достъп",
    startDate: "Начална дата",
    endDate: "Крайна дата",
    confirmApproval: "Потвърди Одобрение",
    expiresOn: "Изтича на",
    accessExpired: "Достъпът е изтекъл"
  },
  en: {
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    firstName: "First Name",
    lastName: "Last Name",
    confirmPass: "Confirm Password",
    home: "Home",
    myTests: "My Tests",
    functions: "Functions",
    contact: "Contact",
    logout: "Logout",
    adminPanel: "Admin Panel",
    welcome: "Welcome to Maritime Tests",
    subWelcome: "Prepare for your exams professionally.",
    startTest: "Start Test",
    requestAccess: "Request Access",
    status: "Status",
    approved: "Approved",
    pending: "Pending",
    price: "Price",
    totalPrice: "Total Price",
    revolutMsg: "Please send the amount to the following Revolut link, using your email as reference:",
    users: "Users",
    categories: "Categories",
    requests: "Requests",
    import: "Import",
    packages: "Packages",
    uploadExcel: "Upload Excel File",
    generateTest: "Generate Test",
    timeLeft: "Time Left",
    submit: "Submit Test",
    send: "Send",
    score: "Score",
    question: "Question",
    prev: "Previous",
    next: "Next",
    suspend: "Suspend",
    activate: "Activate",
    changePass: "Change Password",
    save: "Save",
    cancel: "Cancel",
    noTests: "You have no active categories. Please request access from Functions.",
    completed: "Completed",
    congrats: "Test Finished!",
    failed: "Fail",
    passed: "Pass",
    good: "Good",
    veryGood: "Very Good",
    excellent: "Excellent",
    settings: "Settings",
    revolutLink: "Revolut Link",
    facebookLink: "Facebook Link",
    announcement: "Announcement (Bar)",
    followUs: "Follow us on Facebook",
    contactUs: "Contact Us",
    addCategory: "Add Category",
    addPackage: "Add Package",
    edit: "Edit",
    delete: "Delete",
    nameBg: "Name (BG)",
    nameEn: "Name (EN)",
    duration: "Duration (min)",
    questions: "Questions",
    create: "Create",
    packageIncludes: "Package Includes:",
    individual: "Individual Functions",
    bundle: "PROMO PACKAGES",
    approvalSettings: "Access Settings",
    startDate: "Start Date",
    endDate: "End Date",
    confirmApproval: "Confirm Approval",
    expiresOn: "Expires on",
    accessExpired: "Access Expired"
  }
};